# -*- coding: utf-8 -*-
"""Rock-Paper-Scissors Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDjA2g0yQfvd9mbBgq4530bnLzGLpFq0
"""

import random

# Function to determine the winner
def determine_winner(user_choice, computer_choice):
    if user_choice == computer_choice:
        return "It's a tie!"
    elif (user_choice == "rock" and computer_choice == "scissors") or \
         (user_choice == "scissors" and computer_choice == "paper") or \
         (user_choice == "paper" and computer_choice == "rock"):
        return "You win!"
    else:
        return "You lose!"

# Function to get the computer's choice randomly
def get_computer_choice():
    return random.choice(["rock", "paper", "scissors"])

# Function to display scores
def display_scores(user_score, computer_score):
    print(f"Your score: {user_score} | Computer score: {computer_score}")

# Main function to handle the game flow
def play_game():
    user_score = 0
    computer_score = 0

    print("Welcome to Rock-Paper-Scissors!")
    print("Choose one: rock, paper, or scissors.")

    while True:
        # Ask the user for their choice
        user_choice = input("Enter your choice (rock, paper, or scissors): ").lower()

        # Validate user input
        if user_choice not in ["rock", "paper", "scissors"]:
            print("Invalid input. Please choose rock, paper, or scissors.")
            continue

        # Get the computer's choice
        computer_choice = get_computer_choice()

        # Determine the winner
        result = determine_winner(user_choice, computer_choice)

        # Display choices and result
        print(f"\nYou chose: {user_choice}")
        print(f"The computer chose: {computer_choice}")
        print(result)

        # Update scores
        if result == "You win!":
            user_score += 1
        elif result == "You lose!":
            computer_score += 1

        # Display the current scores
        display_scores(user_score, computer_score)

        # Ask if the user wants to play again
        play_again = input("\nDo you want to play again? (yes/no): ").lower()
        if play_again != "yes":
            print("Thank you for playing! Final scores:")
            display_scores(user_score, computer_score)
            break

if __name__ == "__main__":
    play_game()